[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "calcipy_template"
version = "0.0.1"
description = "Project scaffold for Python packages built on `calcipy`. Utilizes `copier` to keep scaffolding up to date"
license = "MIT"
authors = [ "Kyle King <dev.act.kyle@gmail.com>",]
maintainers = []
repository = "https://github.com/kyleking/calcipy_template"
documentation = "https://github.com/kyleking/calcipy_template"
readme = "README.md"
include = []
keywords = []
classifiers = []

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/kyleking/calcipy_template/issues"

[tool.poetry.dependencies]
python = "^3.8, <3.9"

[tool.poetry.dev-dependencies]
